name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for outdated dependencies
        run: |
          echo "=== Dependency Update Check ==="
          echo "Checking for outdated dependencies..."
          echo "----------------------------------------"
          npm outdated --long || true
          echo "----------------------------------------"
          echo "To update dependencies, run: npm update"
          echo "For major version updates, review package.json and run: npm install <package>@latest"
          echo "=== Check Complete ===" 